import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  BuildingOfficeIcon, 
  MapPinIcon, 
  PhoneIcon, 
  EnvelopeIcon,
  CheckIcon,
  XMarkIcon
} from '@heroicons/react/24/outline';
import { useAuth } from '../../contexts/AuthContext';
import { useTranslation } from 'react-i18next';

interface FormData {
  name: string;
  slug: string;
  sector: string;
  description: string;
  address: string;
  city: string;
  postal_code: string;
  phone: string;
  email: string;
  location_type: 'fixed' | 'mobile';
  booking_enabled: boolean;
  latitude?: number;
  longitude?: number;
}

const CreateFirstPlace: React.FC = () => {
  const navigate = useNavigate();
  const { user, isAuthenticated } = useAuth();
  const { t } = useTranslation();
  const [loading, setLoading] = useState(false);
  const [step, setStep] = useState(1);
  const [formData, setFormData] = useState<FormData>({
    name: '',
    slug: '',
    sector: '',
    description: '',
    address: '',
    city: '',
    postal_code: '',
    phone: '',
    email: '',
    location_type: 'fixed',
    booking_enabled: true,
    latitude: undefined,
    longitude: undefined,
  });

  // Helper function to generate slug from name
  const generateSlug = (text: string): string => {
    return text
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '') // Remove accents
      .replace(/[^a-z0-9\s-]/g, '') // Remove special characters
      .replace(/\s+/g, '-') // Replace spaces with hyphens
      .replace(/-+/g, '-') // Replace multiple hyphens with single
      .trim()
      .replace(/^-+|-+$/g, ''); // Remove leading/trailing hyphens
  };

  // Auto-generate slug when name changes
  useEffect(() => {
    if (formData.name && !formData.slug) {
      const autoSlug = generateSlug(formData.name);
      setFormData(prev => ({ ...prev, slug: autoSlug }));
    }
  }, [formData.name, formData.slug]);

  // Redirect if not authenticated
  useEffect(() => {
    if (!isAuthenticated) {
      navigate('/login');
    }
  }, [isAuthenticated, navigate]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value, type } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? (e.target as HTMLInputElement).checked : value
    }));
  };

  const handleLocationTypeChange = (type: 'fixed' | 'mobile') => {
    setFormData(prev => ({ ...prev, location_type: type }));
  };

  const getCurrentLocation = () => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          setFormData(prev => ({
            ...prev,
            latitude: position.coords.latitude,
            longitude: position.coords.longitude
          }));
        },
        () => {
          alert('Unable to get your location. Please enter coordinates manually.');
        }
      );
    } else {
      alert('Geolocation is not supported by this browser.');
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    const token = localStorage.getItem('auth_token');
    if (!token) {
      alert('You must be logged in to create a place. Please log in first.');
      return;
    }

    try {
      setLoading(true);
      
      const placeData = {
        codigo: null,
        nome: formData.name,
        slug: formData.slug || undefined, // Auto-generated by backend if not provided
        tipo: formData.sector,
        about: formData.description,
        rua: formData.address,
        cidade: formData.city,
        cod_postal: formData.postal_code,
        telefone: formData.phone,
        email: formData.email,
        booking_enabled: formData.booking_enabled,
        pais: 'Portugal',
        regiao: formData.sector,
        porta: '',
        website: '',
        instagram: '',
        is_bio_diamond: false,
        latitude: formData.latitude || null,
        longitude: formData.longitude || null,
        working_hours: {}
      };

      const response = await fetch('/api/v1/owner/places', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify(placeData)
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to create place');
      }

      const newPlace = await response.json();
      console.log('✅ Place created successfully:', newPlace);
      
      // Redirect to places management
      navigate('/owner/places');
    } catch (error) {
      console.error('❌ Error creating place:', error);
      alert('Failed to create place: ' + (error as Error).message);
    } finally {
      setLoading(false);
    }
  };

  const nextStep = () => {
    if (step < 3) setStep(step + 1);
  };

  const prevStep = () => {
    if (step > 1) setStep(step - 1);
  };

  const isStepValid = (stepNumber: number) => {
    switch (stepNumber) {
      case 1:
        return formData.name.trim() !== '' && formData.sector.trim() !== '';
      case 2:
        return formData.address.trim() !== '' && formData.city.trim() !== '';
      case 3:
        return true; // Optional step
      default:
        return false;
    }
  };

  if (!isAuthenticated) {
    return (
      <div className="min-h-screen flex items-center justify-center" style={{backgroundColor: '#F5F5F5'}}>
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-[#1E90FF] mx-auto"></div>
          <p className="mt-4 text-[#333333]" style={{ fontFamily: 'Open Sans, sans-serif' }}>Loading...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen" style={{backgroundColor: '#F5F5F5'}}>
      <div className="max-w-4xl mx-auto px-4 py-8">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-20 h-20 rounded-full mb-6" style={{backgroundColor: '#1E90FF'}}>
            <BuildingOfficeIcon className="h-10 w-10 text-white" />
          </div>
          <h1 className="text-3xl font-bold mb-2" style={{ fontFamily: 'Poppins, sans-serif', color: '#333333' }}>{t('owner.dashboard.createFirstPlaceTitle')}</h1>
          <p className="text-lg" style={{ fontFamily: 'Open Sans, sans-serif', color: '#9E9E9E' }}>
            {t('owner.dashboard.createFirstPlaceSubtitle')}
          </p>
        </div>

        {/* Progress Steps */}
        <div className="mb-8">
          <div className="flex items-center justify-center space-x-4">
            {[1, 2, 3].map((stepNumber) => (
              <React.Fragment key={stepNumber}>
                <div className="flex items-center">
                  <div 
                    className="w-10 h-10 rounded-full flex items-center justify-center text-sm font-semibold"
                    style={{
                      backgroundColor: step >= stepNumber ? '#1E90FF' : '#E0E0E0',
                      color: step >= stepNumber ? '#FFFFFF' : '#9E9E9E'
                    }}
                  >
                    {step > stepNumber ? (
                      <CheckIcon className="h-5 w-5" />
                    ) : (
                      stepNumber
                    )}
                  </div>
                  <span 
                    className="ml-2 text-sm font-medium"
                    style={{
                      fontFamily: 'Open Sans, sans-serif',
                      fontWeight: 500,
                      color: step >= stepNumber ? '#333333' : '#9E9E9E'
                    }}
                  >
                    {stepNumber === 1 && t('owner.dashboard.basicInfo')}
                    {stepNumber === 2 && t('owner.dashboard.location')}
                    {stepNumber === 3 && t('owner.dashboard.contact')}
                  </span>
                </div>
                {stepNumber < 3 && (
                  <div 
                    className="w-8 h-0.5"
                    style={{
                      backgroundColor: step > stepNumber ? '#1E90FF' : '#E0E0E0'
                    }}
                  />
                )}
              </React.Fragment>
            ))}
          </div>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="space-y-8">
          <div 
            className="rounded-lg p-8"
            style={{
              backgroundColor: '#FFFFFF',
              boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.1)',
              border: '1px solid #E0E0E0'
            }}
          >
            {/* Step 1: Basic Information */}
            {step === 1 && (
              <div className="space-y-6">
                <div>
                  <h2 className="text-xl font-semibold mb-4" style={{ fontFamily: 'Poppins, sans-serif', color: '#333333' }}>{t('owner.dashboard.basicInformation')}</h2>
                  <p className="mb-6" style={{ fontFamily: 'Open Sans, sans-serif', color: '#9E9E9E' }}>{t('owner.dashboard.basicInformationDescription')}</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label className="block text-sm font-medium mb-2" style={{ fontFamily: 'Open Sans, sans-serif', fontWeight: 500, color: '#333333' }}>
                      {t('owner.dashboard.businessName')} *
                    </label>
                    <input
                      type="text"
                      name="name"
                      required
                      value={formData.name}
                      onChange={handleInputChange}
                      className="w-full px-4 py-3 rounded-lg transition-all duration-200"
                      style={{
                        backgroundColor: '#F5F5F5',
                        border: '1px solid #E0E0E0',
                        color: '#333333',
                        fontFamily: 'Open Sans, sans-serif',
                        fontSize: '14px'
                      }}
                      placeholder="Enter your business name"
                      onFocus={(e) => {
                        e.target.style.borderColor = '#1E90FF';
                        e.target.style.boxShadow = '0 0 4px rgba(30, 144, 255, 0.4)';
                      }}
                      onBlur={(e) => {
                        e.target.style.borderColor = '#E0E0E0';
                        e.target.style.boxShadow = 'none';
                      }}
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium mb-2" style={{ fontFamily: 'Open Sans, sans-serif', fontWeight: 500, color: '#333333' }}>
                      {t('owner.dashboard.businessUrlSlug')}
                    </label>
                    <div className="relative">
                      <span className="absolute left-4 top-3 text-sm z-10" style={{ fontFamily: 'Open Sans, sans-serif', color: '#9E9E9E' }}>
                        linkuup.portugalexpatdirectory.com/
                      </span>
                      <input
                        type="text"
                        name="slug"
                        value={formData.slug}
                        onChange={(e) => {
                          const value = e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, '');
                          setFormData(prev => ({ ...prev, slug: value }));
                        }}
                        className="w-full pl-[280px] pr-4 py-3 rounded-lg transition-all duration-200"
                        style={{
                          backgroundColor: '#F5F5F5',
                          border: '1px solid #E0E0E0',
                          color: '#333333',
                          fontFamily: 'Open Sans, sans-serif',
                          fontSize: '14px'
                        }}
                        placeholder="auto-generated-slug"
                        pattern="[a-z0-9\-]+"
                        onFocus={(e) => {
                          e.target.style.borderColor = '#1E90FF';
                          e.target.style.boxShadow = '0 0 4px rgba(30, 144, 255, 0.4)';
                        }}
                        onBlur={(e) => {
                          e.target.style.borderColor = '#E0E0E0';
                          e.target.style.boxShadow = 'none';
                        }}
                      />
                    </div>
                    <p className="mt-1 text-xs" style={{ fontFamily: 'Open Sans, sans-serif', color: '#9E9E9E' }}>
                      {t('owner.dashboard.businessUrlSlugHint')}
                    </p>
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium mb-2" style={{ fontFamily: 'Open Sans, sans-serif', fontWeight: 500, color: '#333333' }}>
                    {t('owner.dashboard.businessSector')} *
                  </label>
                  <select
                    name="sector"
                    required
                    value={formData.sector}
                    onChange={handleInputChange}
                    className="w-full px-4 py-3 rounded-lg transition-all duration-200"
                    style={{
                      backgroundColor: '#F5F5F5',
                      border: '1px solid #E0E0E0',
                      color: '#333333',
                      fontFamily: 'Open Sans, sans-serif',
                      fontSize: '14px'
                    }}
                    onFocus={(e) => {
                      e.target.style.borderColor = '#1E90FF';
                      e.target.style.boxShadow = '0 0 4px rgba(30, 144, 255, 0.4)';
                    }}
                    onBlur={(e) => {
                      e.target.style.borderColor = '#E0E0E0';
                      e.target.style.boxShadow = 'none';
                    }}
                  >
                      <option value="">{t('search.selectService')}</option>
                      <option value="allServices">{t('search.allServices')}</option>
                      <option value="salon">{t('search.salon')}</option>
                      <option value="barber">{t('search.barber')}</option>
                      <option value="nails">{t('search.nails')}</option>
                      <option value="spaSauna">{t('search.spaSauna')}</option>
                      <option value="medicalSpa">{t('search.medicalSpa')}</option>
                      <option value="massage">{t('search.massage')}</option>
                      <option value="fitnessRehab">{t('search.fitnessRehab')}</option>
                      <option value="physiotherapy">{t('search.physiotherapy')}</option>
                      <option value="medicalOffices">{t('search.medicalOffices')}</option>
                      <option value="tattooPiercing">{t('search.tattooPiercing')}</option>
                      <option value="petGrooming">{t('search.petGrooming')}</option>
                      <option value="tanningClinic">{t('search.tanningClinic')}</option>
                    </select>
                </div>

                <div>
                  <label className="block text-sm font-medium mb-2" style={{ fontFamily: 'Open Sans, sans-serif', fontWeight: 500, color: '#333333' }}>
                    {t('owner.dashboard.businessDescription')}
                  </label>
                  <textarea
                    name="description"
                    value={formData.description}
                    onChange={handleInputChange}
                    rows={4}
                    className="w-full px-4 py-3 rounded-lg transition-all duration-200"
                    style={{
                      backgroundColor: '#F5F5F5',
                      border: '1px solid #E0E0E0',
                      color: '#333333',
                      fontFamily: 'Open Sans, sans-serif',
                      fontSize: '14px'
                    }}
                    placeholder={t('owner.dashboard.businessDescriptionPlaceholder')}
                    onFocus={(e) => {
                      e.target.style.borderColor = '#1E90FF';
                      e.target.style.boxShadow = '0 0 4px rgba(30, 144, 255, 0.4)';
                    }}
                    onBlur={(e) => {
                      e.target.style.borderColor = '#E0E0E0';
                      e.target.style.boxShadow = 'none';
                    }}
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium mb-4" style={{ fontFamily: 'Open Sans, sans-serif', fontWeight: 500, color: '#333333' }}>
                    {t('owner.dashboard.locationType')}
                  </label>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <button
                      type="button"
                      onClick={() => handleLocationTypeChange('fixed')}
                      className="p-4 rounded-lg border-2 transition-all duration-200"
                      style={{
                        borderColor: formData.location_type === 'fixed' ? '#1E90FF' : '#E0E0E0',
                        backgroundColor: formData.location_type === 'fixed' ? 'rgba(30, 144, 255, 0.1)' : '#F5F5F5'
                      }}
                      onMouseEnter={(e) => {
                        if (formData.location_type !== 'fixed') {
                          e.currentTarget.style.borderColor = '#1E90FF';
                        }
                      }}
                      onMouseLeave={(e) => {
                        if (formData.location_type !== 'fixed') {
                          e.currentTarget.style.borderColor = '#E0E0E0';
                        }
                      }}
                    >
                      <div className="flex items-center space-x-3">
                        <BuildingOfficeIcon className="h-6 w-6" style={{ color: formData.location_type === 'fixed' ? '#1E90FF' : '#333333' }} />
                        <div className="text-left">
                          <div className="font-medium" style={{ fontFamily: 'Open Sans, sans-serif', color: '#333333' }}>{t('owner.dashboard.fixedLocation')}</div>
                          <div className="text-sm" style={{ fontFamily: 'Open Sans, sans-serif', color: '#9E9E9E' }}>{t('owner.dashboard.fixedLocationDescription')}</div>
                        </div>
                      </div>
                    </button>

                    <button
                      type="button"
                      onClick={() => handleLocationTypeChange('mobile')}
                      className="p-4 rounded-lg border-2 transition-all duration-200"
                      style={{
                        borderColor: formData.location_type === 'mobile' ? '#1E90FF' : '#E0E0E0',
                        backgroundColor: formData.location_type === 'mobile' ? 'rgba(30, 144, 255, 0.1)' : '#F5F5F5'
                      }}
                      onMouseEnter={(e) => {
                        if (formData.location_type !== 'mobile') {
                          e.currentTarget.style.borderColor = '#1E90FF';
                        }
                      }}
                      onMouseLeave={(e) => {
                        if (formData.location_type !== 'mobile') {
                          e.currentTarget.style.borderColor = '#E0E0E0';
                        }
                      }}
                    >
                      <div className="flex items-center space-x-3">
                        <MapPinIcon className="h-6 w-6" style={{ color: formData.location_type === 'mobile' ? '#1E90FF' : '#333333' }} />
                        <div className="text-left">
                          <div className="font-medium" style={{ fontFamily: 'Open Sans, sans-serif', color: '#333333' }}>{t('owner.dashboard.mobileService')}</div>
                          <div className="text-sm" style={{ fontFamily: 'Open Sans, sans-serif', color: '#9E9E9E' }}>{t('owner.dashboard.mobileServiceDescription')}</div>
                        </div>
                      </div>
                    </button>
                  </div>
                </div>
              </div>
            )}

            {/* Step 2: Location */}
            {step === 2 && (
              <div className="space-y-6">
                <div>
                  <h2 className="text-xl font-semibold mb-4" style={{ fontFamily: 'Poppins, sans-serif', color: '#333333' }}>{t('owner.dashboard.locationDetails')}</h2>
                  <p className="mb-6" style={{ fontFamily: 'Open Sans, sans-serif', color: '#9E9E9E' }}>{t('owner.dashboard.locationDetailsDescription')}</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label className="block text-sm font-medium mb-2" style={{ fontFamily: 'Open Sans, sans-serif', fontWeight: 500, color: '#333333' }}>
                      {t('owner.dashboard.address')} *
                    </label>
                    <input
                      type="text"
                      name="address"
                      required
                      value={formData.address}
                      onChange={handleInputChange}
                      className="w-full px-4 py-3 rounded-lg transition-all duration-200"
                      style={{
                        backgroundColor: '#F5F5F5',
                        border: '1px solid #E0E0E0',
                        color: '#333333',
                        fontFamily: 'Open Sans, sans-serif',
                        fontSize: '14px'
                      }}
                      placeholder="Street address"
                      onFocus={(e) => {
                        e.target.style.borderColor = '#1E90FF';
                        e.target.style.boxShadow = '0 0 4px rgba(30, 144, 255, 0.4)';
                      }}
                      onBlur={(e) => {
                        e.target.style.borderColor = '#E0E0E0';
                        e.target.style.boxShadow = 'none';
                      }}
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium mb-2" style={{ fontFamily: 'Open Sans, sans-serif', fontWeight: 500, color: '#333333' }}>
                      {t('owner.dashboard.city')} *
                    </label>
                    <input
                      type="text"
                      name="city"
                      required
                      value={formData.city}
                      onChange={handleInputChange}
                      className="w-full px-4 py-3 rounded-lg transition-all duration-200"
                      style={{
                        backgroundColor: '#F5F5F5',
                        border: '1px solid #E0E0E0',
                        color: '#333333',
                        fontFamily: 'Open Sans, sans-serif',
                        fontSize: '14px'
                      }}
                      placeholder="City"
                      onFocus={(e) => {
                        e.target.style.borderColor = '#1E90FF';
                        e.target.style.boxShadow = '0 0 4px rgba(30, 144, 255, 0.4)';
                      }}
                      onBlur={(e) => {
                        e.target.style.borderColor = '#E0E0E0';
                        e.target.style.boxShadow = 'none';
                      }}
                    />
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label className="block text-sm font-medium mb-2" style={{ fontFamily: 'Open Sans, sans-serif', fontWeight: 500, color: '#333333' }}>
                      {t('owner.dashboard.postalCode')}
                    </label>
                    <input
                      type="text"
                      name="postal_code"
                      value={formData.postal_code}
                      onChange={handleInputChange}
                      className="w-full px-4 py-3 rounded-lg transition-all duration-200"
                      style={{
                        backgroundColor: '#F5F5F5',
                        border: '1px solid #E0E0E0',
                        color: '#333333',
                        fontFamily: 'Open Sans, sans-serif',
                        fontSize: '14px'
                      }}
                      placeholder="1234-567"
                      onFocus={(e) => {
                        e.target.style.borderColor = '#1E90FF';
                        e.target.style.boxShadow = '0 0 4px rgba(30, 144, 255, 0.4)';
                      }}
                      onBlur={(e) => {
                        e.target.style.borderColor = '#E0E0E0';
                        e.target.style.boxShadow = 'none';
                      }}
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium mb-2" style={{ fontFamily: 'Open Sans, sans-serif', fontWeight: 500, color: '#333333' }}>
                      {t('owner.dashboard.coordinatesOptional')}
                    </label>
                    <div className="flex space-x-2">
                      <input
                        type="number"
                        step="any"
                        value={formData.latitude || ''}
                        onChange={(e) => setFormData(prev => ({ 
                          ...prev, 
                          latitude: e.target.value ? parseFloat(e.target.value) : undefined 
                        }))}
                        className="flex-1 px-4 py-3 rounded-lg transition-all duration-200"
                        style={{
                          backgroundColor: '#F5F5F5',
                          border: '1px solid #E0E0E0',
                          color: '#333333',
                          fontFamily: 'Open Sans, sans-serif',
                          fontSize: '14px'
                        }}
                        placeholder={t('owner.dashboard.latitude')}
                        onFocus={(e) => {
                          e.target.style.borderColor = '#1E90FF';
                          e.target.style.boxShadow = '0 0 4px rgba(30, 144, 255, 0.4)';
                        }}
                        onBlur={(e) => {
                          e.target.style.borderColor = '#E0E0E0';
                          e.target.style.boxShadow = 'none';
                        }}
                      />
                      <input
                        type="number"
                        step="any"
                        value={formData.longitude || ''}
                        onChange={(e) => setFormData(prev => ({ 
                          ...prev, 
                          longitude: e.target.value ? parseFloat(e.target.value) : undefined 
                        }))}
                        className="flex-1 px-4 py-3 rounded-lg transition-all duration-200"
                        style={{
                          backgroundColor: '#F5F5F5',
                          border: '1px solid #E0E0E0',
                          color: '#333333',
                          fontFamily: 'Open Sans, sans-serif',
                          fontSize: '14px'
                        }}
                        placeholder={t('owner.dashboard.longitude')}
                        onFocus={(e) => {
                          e.target.style.borderColor = '#1E90FF';
                          e.target.style.boxShadow = '0 0 4px rgba(30, 144, 255, 0.4)';
                        }}
                        onBlur={(e) => {
                          e.target.style.borderColor = '#E0E0E0';
                          e.target.style.boxShadow = 'none';
                        }}
                      />
                    </div>
                    <button
                      type="button"
                      onClick={getCurrentLocation}
                      className="mt-2 text-sm transition-colors duration-200"
                      style={{ fontFamily: 'Open Sans, sans-serif', color: '#1E90FF' }}
                      onMouseEnter={(e) => e.currentTarget.style.color = '#1877D2'}
                      onMouseLeave={(e) => e.currentTarget.style.color = '#1E90FF'}
                    >
                      {t('owner.dashboard.useCurrentLocation')}
                    </button>
                  </div>
                </div>
              </div>
            )}

            {/* Step 3: Contact Information */}
            {step === 3 && (
              <div className="space-y-6">
                <div>
                  <h2 className="text-xl font-semibold mb-4" style={{ fontFamily: 'Poppins, sans-serif', color: '#333333' }}>{t('owner.dashboard.contactInformation')}</h2>
                  <p className="mb-6" style={{ fontFamily: 'Open Sans, sans-serif', color: '#9E9E9E' }}>{t('owner.dashboard.contactInformationDescription')}</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label className="block text-sm font-medium mb-2" style={{ fontFamily: 'Open Sans, sans-serif', fontWeight: 500, color: '#333333' }}>
                      {t('owner.dashboard.phoneNumber')}
                    </label>
                    <div className="relative">
                      <PhoneIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5" style={{ color: '#9E9E9E' }} />
                      <input
                        type="tel"
                        name="phone"
                        value={formData.phone}
                        onChange={handleInputChange}
                        className="w-full pl-10 pr-4 py-3 rounded-lg transition-all duration-200"
                        style={{
                          backgroundColor: '#F5F5F5',
                          border: '1px solid #E0E0E0',
                          color: '#333333',
                          fontFamily: 'Open Sans, sans-serif',
                          fontSize: '14px'
                        }}
                        placeholder="+351 123 456 789"
                        onFocus={(e) => {
                          e.target.style.borderColor = '#1E90FF';
                          e.target.style.boxShadow = '0 0 4px rgba(30, 144, 255, 0.4)';
                        }}
                        onBlur={(e) => {
                          e.target.style.borderColor = '#E0E0E0';
                          e.target.style.boxShadow = 'none';
                        }}
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block text-sm font-medium mb-2" style={{ fontFamily: 'Open Sans, sans-serif', fontWeight: 500, color: '#333333' }}>
                      {t('owner.dashboard.emailAddress')}
                    </label>
                    <div className="relative">
                      <EnvelopeIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5" style={{ color: '#9E9E9E' }} />
                      <input
                        type="email"
                        name="email"
                        value={formData.email}
                        onChange={handleInputChange}
                        className="w-full pl-10 pr-4 py-3 rounded-lg transition-all duration-200"
                        style={{
                          backgroundColor: '#F5F5F5',
                          border: '1px solid #E0E0E0',
                          color: '#333333',
                          fontFamily: 'Open Sans, sans-serif',
                          fontSize: '14px'
                        }}
                        placeholder="business@example.com"
                        onFocus={(e) => {
                          e.target.style.borderColor = '#1E90FF';
                          e.target.style.boxShadow = '0 0 4px rgba(30, 144, 255, 0.4)';
                        }}
                        onBlur={(e) => {
                          e.target.style.borderColor = '#E0E0E0';
                          e.target.style.boxShadow = 'none';
                        }}
                      />
                    </div>
                  </div>
                </div>

                <div className="flex items-center space-x-3">
                  <input
                    type="checkbox"
                    name="booking_enabled"
                    checked={formData.booking_enabled}
                    onChange={handleInputChange}
                    className="h-4 w-4 rounded"
                    style={{
                      accentColor: '#1E90FF'
                    }}
                  />
                  <label style={{ fontFamily: 'Open Sans, sans-serif', color: '#333333' }}>
                    {t('owner.dashboard.enableOnlineBooking')}
                  </label>
                </div>
              </div>
            )}

            {/* Navigation Buttons */}
            <div className="flex justify-between pt-6" style={{ borderTop: '1px solid #E0E0E0' }}>
              <button
                type="button"
                onClick={prevStep}
                disabled={step === 1}
                className="px-6 py-3 rounded-lg font-medium transition-all duration-200"
                style={{
                  fontFamily: 'Open Sans, sans-serif',
                  fontWeight: 500,
                  backgroundColor: step === 1 ? '#E0E0E0' : '#F5F5F5',
                  color: step === 1 ? '#9E9E9E' : '#333333',
                  border: '1px solid #E0E0E0',
                  cursor: step === 1 ? 'not-allowed' : 'pointer'
                }}
                onMouseEnter={(e) => {
                  if (step !== 1) {
                    e.currentTarget.style.backgroundColor = '#E0E0E0';
                  }
                }}
                onMouseLeave={(e) => {
                  if (step !== 1) {
                    e.currentTarget.style.backgroundColor = '#F5F5F5';
                  }
                }}
              >
                {t('owner.dashboard.previous')}
              </button>

              <div className="flex space-x-3">
                <button
                  type="button"
                  onClick={() => navigate('/owner/dashboard')}
                  className="px-6 py-3 rounded-lg font-medium transition-all duration-200"
                  style={{
                    fontFamily: 'Open Sans, sans-serif',
                    fontWeight: 500,
                    backgroundColor: '#F5F5F5',
                    color: '#333333',
                    border: '1px solid #E0E0E0'
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.backgroundColor = '#E0E0E0';
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.backgroundColor = '#F5F5F5';
                  }}
                >
                  {t('owner.dashboard.cancel')}
                </button>

                {step < 3 ? (
                  <button
                    type="button"
                    onClick={nextStep}
                    disabled={!isStepValid(step)}
                    className="px-6 py-3 rounded-lg font-medium transition-all duration-200"
                    style={{
                      fontFamily: 'Open Sans, sans-serif',
                      fontWeight: 600,
                      backgroundColor: isStepValid(step) ? '#1E90FF' : '#E0E0E0',
                      color: isStepValid(step) ? '#FFFFFF' : '#9E9E9E',
                      cursor: isStepValid(step) ? 'pointer' : 'not-allowed'
                    }}
                    onMouseEnter={(e) => {
                      if (isStepValid(step)) {
                        e.currentTarget.style.backgroundColor = '#1877D2';
                      }
                    }}
                    onMouseLeave={(e) => {
                      if (isStepValid(step)) {
                        e.currentTarget.style.backgroundColor = '#1E90FF';
                      }
                    }}
                  >
                    {t('owner.dashboard.next')}
                  </button>
                ) : (
                  <button
                    type="submit"
                    disabled={loading}
                    className="px-8 py-3 rounded-lg font-medium transition-all duration-200"
                    style={{
                      fontFamily: 'Open Sans, sans-serif',
                      fontWeight: 600,
                      backgroundColor: loading ? '#E0E0E0' : '#FF5A5F',
                      color: loading ? '#9E9E9E' : '#FFFFFF',
                      cursor: loading ? 'not-allowed' : 'pointer'
                    }}
                    onMouseEnter={(e) => {
                      if (!loading) {
                        e.currentTarget.style.backgroundColor = '#E53E3E';
                      }
                    }}
                    onMouseLeave={(e) => {
                      if (!loading) {
                        e.currentTarget.style.backgroundColor = '#FF5A5F';
                      }
                    }}
                  >
                    {loading ? (
                      <div className="flex items-center space-x-2">
                        <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                        <span>{t('owner.dashboard.creating')}</span>
                      </div>
                    ) : (
                      t('owner.dashboard.createPlace')
                    )}
                  </button>
                )}
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
};

export default CreateFirstPlace;
